version: "3.8"
services:
  process-psql:
    image: ${PROCESS_IMAGE}
    environment:
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - CLIENTS_FILE=${CLIENTS_FILE}
      - USERS_FILE=${USERS_FILE}
      - GROUPS_FILE=${GROUPS_FILE}
    volumes:
      - ./clients.csv:/home/process-psql/clients.csv
      - ./users.csv:/home/process-psql/users.csv
      - ./groups.csv:/home/process-psql/groups.csv


