version: "3.8"

services:
  freeradius:
    image: ${RADIUS_IMAGE}
    build:
      context: images
      dockerfile: freeradius/Dockerfile
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    environment:
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=5${DB_PORT}
    volumes:
      - ./radius/data:/var/lib/raduisd
    networks:
      - radius
    depends_on:
      - postgres  

  postgres:
    image: ${DB_IMAGE}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./postgresql/sql:/docker-entrypoint-initdb.d
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - radius

networks:
  radius:
